# Generated by Django 3.2.5 on 2021-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
    ]
