# Generated by Django 3.2.5 on 2021-07-05 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, choices=[('HORISTA', 'Horista'), ('MENSALISTA', 'Mensalista'), ('COMISSIONADO', 'Comissionado')], max_length=12)),
                ('salario', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('sindicato', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PontoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ponto', models.DateField(null=True)),
                ('hora_entrada', models.TimeField(null=True)),
                ('hora_saida', models.TimeField(null=True)),
            ],
        ),
    ]
