# Generated by Django 3.2.5 on 2021-08-15 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, choices=[('HORISTA', 'Horista'), ('MENSALISTA', 'Mensalista'), ('COMISSIONADO', 'Comissionado')], max_length=12)),
                ('salario', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('sindicato', models.BooleanField(null=True)),
                ('forma_pagamento', models.CharField(choices=[('CHEQUE', 'Cheque'), ('CHEQUE-CORREIOS', 'Cheque-Correios'), ('DEPOSITO', 'Deposito')], max_length=20)),
                ('comissao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_a_receber', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('taxa_sindicato', models.IntegerField(null=True)),
                ('mes_pago', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=30)),
                ('descricao_item', models.CharField(max_length=1000)),
                ('data_venda', models.DateField(null=True)),
                ('valor_venda', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('is_active', models.BooleanField(null=True)),
                ('mes_venda', models.IntegerField(null=True)),
                ('is_paid', models.BooleanField(null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='PontoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ponto', models.DateField(null=True)),
                ('hora_entrada', models.TimeField(null=True)),
                ('hora_saida', models.TimeField(null=True)),
                ('horas_trabalhadas', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('mes_ponto', models.IntegerField(null=True)),
                ('is_paid', models.BooleanField(null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
        ),
    ]
