# Generated by Django 3.2.5 on 2021-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_ponto',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='hora_saida',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hora_entrada',
            field=models.TimeField(null=True),
        ),
    ]
