# Generated by Django 3.2.5 on 2021-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_funcionario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('HORISTA', 'Horista'), ('MENSALISTA', 'Mensalista'), ('COMISSIONADO', 'Comissionado')], max_length=12),
        ),
    ]
