# Generated by Django 3.2.5 on 2021-07-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210704_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='hora_entrada',
            field=models.TimeField(),
        ),
    ]
