# Generated by Django 3.2.5 on 2021-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_funcionario_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sindicato',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Nao')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('HORISTA', 'Horista'), ('MENSALISTA', 'Mensalista'), ('COMISSIONADO', 'Comissionado')], max_length=12),
        ),
    ]
