# Generated by Django 3.2.5 on 2021-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210917_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pontofuncionario',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
