# Generated by Django 3.2.5 on 2021-07-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pontofuncionario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CHEQUE', 'Cheque'), ('CHEQUE-CORREIOS', 'Cheque-Correios'), ('DEPOSITO', 'Deposito')], max_length=20),
        ),
    ]
