# Generated by Django 3.2.5 on 2021-07-21 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='comissao',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pontofuncionario',
            name='pagamento',
            field=models.IntegerField(null=True),
        ),
    ]
