# Generated by Django 3.2.5 on 2021-07-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_funcionario_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontofuncionario',
            name='ativo',
            field=models.BooleanField(null=True),
        ),
    ]
