# Generated by Django 3.2.5 on 2021-07-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210721_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pontofuncionario',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
