# Generated by Django 3.2.5 on 2021-07-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210721_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontofuncionario',
            old_name='pagamento',
            new_name='horas_trabalhadas',
        ),
    ]
