# Generated by Django 3.2.5 on 2021-07-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_pagamento_pontofuncionario_horas_trabalhadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontofuncionario',
            name='total_a_receber',
            field=models.IntegerField(null=True),
        ),
    ]
