# Generated by Django 3.2.5 on 2021-07-23 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_pagamento_pontofuncionario_horas_trabalhadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='total_a_receber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='comissao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='forma_pagamento',
            field=models.CharField(choices=[('CHEQUE', 'Cheque'), ('CHEQUE-CORREIOS', 'Cheque-Correios'), ('DEPOSITO', 'Deposito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
