# Generated by Django 3.2.5 on 2021-07-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pontofuncionario_total_a_receber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontofuncionario',
            name='total_a_receber',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='total_a_receber',
            field=models.IntegerField(null=True),
        ),
    ]
