# Generated by Django 3.2.5 on 2021-07-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210725_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
    ]
