# Generated by Django 3.2.5 on 2021-08-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_funcionario_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='mes_pago',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='taxa_sindicato',
            field=models.IntegerField(null=True),
        ),
    ]
