# Generated by Django 3.2.5 on 2021-07-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210722_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='forma_pagamento',
            field=models.CharField(choices=[('CHEQUE', 'Cheque'), ('CHEQUE-CORREIOS', 'Cheque-Correios'), ('DEPOSITO', 'Deposito')], max_length=20),
        ),
    ]
