# Generated by Django 3.2.5 on 2021-08-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210809_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontofuncionario',
            name='mes_ponto',
            field=models.IntegerField(null=True),
        ),
    ]
