# Generated by Django 3.2.5 on 2021-08-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_venda_mes_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontofuncionario',
            name='is_paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='is_paid',
            field=models.BooleanField(null=True),
        ),
    ]
